import { Category, MenuItem, Restaurant, Table, ThemeConfig } from '../types/index.js';

export const VEG_THEME_PRESET: ThemeConfig = {
  preset: 'VEG_THEME',
  restaurantName: 'Verde Botanica',
  restaurantLogo: '🌿',
  tagline: 'Fresh • Organic • Pure Vegetarian Culinary Craft',
  colors: {
    primary: '#059669', // Emerald 600
    primaryLight: '#34d399', // Emerald 400
    primaryDark: '#065f46', // Emerald 800
    secondary: '#10b981', // Emerald 500
    accent: '#84cc16', // Lime 500
    bgPrimary: '#f8fafc', // Slate 50
    bgSecondary: '#ecfdf5', // Emerald 50
    bgCard: '#ffffff',
    textPrimary: '#0f172a', // Slate 900
    textSecondary: '#334155', // Slate 700
    textMuted: '#64748b', // Slate 500
    border: '#e2e8f0',
    surfaceElevated: '#ffffff',
  },
  typography: {
    headingFont: 'Fraunces, serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    style: 'classic',
  },
  cardStyle: 'bordered',
  buttonStyle: 'rounded-lg',
  animationStyle: 'smooth',
  foodPresentationStyle: 'grid-modern',
  heroBannerUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
};

export const NON_VEG_THEME_PRESET: ThemeConfig = {
  preset: 'NON_VEG_THEME',
  restaurantName: 'The Ember & Smokehouse',
  restaurantLogo: '🔥',
  tagline: 'Artisan Wood-Fired Tandoor & Prime Cut Specialists',
  colors: {
    primary: '#ea580c', // Orange 600
    primaryLight: '#fb923c', // Orange 400
    primaryDark: '#9a3412', // Orange 800
    secondary: '#b91c1c', // Red 700
    accent: '#f59e0b', // Amber 500
    bgPrimary: '#090d16', // Deep dark obsidian
    bgSecondary: '#131b2e', // Slate 850
    bgCard: '#151f33',
    textPrimary: '#f8fafc', // Slate 50
    textSecondary: '#cbd5e1', // Slate 300
    textMuted: '#94a3b8', // Slate 400
    border: '#2a3754',
    surfaceElevated: '#1a2742',
  },
  typography: {
    headingFont: 'Syne, sans-serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    style: 'modern',
  },
  cardStyle: 'glassmorphism',
  buttonStyle: 'rounded-lg',
  animationStyle: 'energetic',
  foodPresentationStyle: 'showcase-cards',
  heroBannerUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
};

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-verde-01',
    slug: 'verde-botanica',
    name: 'Verde Botanica',
    tagline: 'Farm-to-Table Pure Vegetarian & Artisanal Dining',
    logoUrl: '🌿',
    coverImageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
    phone: '+91 98200 12345',
    email: 'hello@verdebotanica.com',
    address: '42 Lotus Promenade, Indiranagar, Bengaluru',
    currency: 'INR',
    currencySymbol: '₹',
    taxRate: 0.05, // 5% GST
    serviceFeeRate: 0.00,
    themePreset: 'VEG_THEME',
    themeConfig: VEG_THEME_PRESET,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rest-ember-02',
    slug: 'ember-smokehouse',
    name: 'The Ember & Smokehouse',
    tagline: 'Slow-Smoked Meats & Wood-Fired Prime Tandoor Grill',
    logoUrl: '🔥',
    coverImageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    phone: '+91 98110 54321',
    email: 'reservations@embersmoke.com',
    address: '77 Copper Mill Road, Cyber Hub, Gurugram',
    currency: 'INR',
    currencySymbol: '₹',
    taxRate: 0.05,
    serviceFeeRate: 0.00,
    themePreset: 'NON_VEG_THEME',
    themeConfig: NON_VEG_THEME_PRESET,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_TABLES: Table[] = [
  // Verde Botanica Tables
  {
    id: 'tbl-verde-12',
    restaurantId: 'rest-verde-01',
    tableNumber: '12',
    tableName: 'Garden Bay 12',
    capacity: 4,
    qrCodeUrl: '/restaurant/verde-botanica/table/12',
    status: 'AVAILABLE',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tbl-verde-01',
    restaurantId: 'rest-verde-01',
    tableNumber: '1',
    tableName: 'Terrace Window 1',
    capacity: 2,
    qrCodeUrl: '/restaurant/verde-botanica/table/1',
    status: 'AVAILABLE',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tbl-verde-02',
    restaurantId: 'rest-verde-01',
    tableNumber: '2',
    tableName: 'Atrium Center 2',
    capacity: 4,
    qrCodeUrl: '/restaurant/verde-botanica/table/2',
    status: 'AVAILABLE',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tbl-verde-03',
    restaurantId: 'rest-verde-01',
    tableNumber: '3',
    tableName: 'Courtyard Booth 3',
    capacity: 6,
    qrCodeUrl: '/restaurant/verde-botanica/table/3',
    status: 'AVAILABLE',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Ember Smokehouse Tables
  {
    id: 'tbl-ember-01',
    restaurantId: 'rest-ember-02',
    tableNumber: '1',
    tableName: 'Firepit Booth 1',
    capacity: 4,
    qrCodeUrl: '/restaurant/ember-smokehouse/table/1',
    status: 'AVAILABLE',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tbl-ember-02',
    restaurantId: 'rest-ember-02',
    tableNumber: '2',
    tableName: 'Lodge High-Top 2',
    capacity: 2,
    qrCodeUrl: '/restaurant/ember-smokehouse/table/2',
    status: 'AVAILABLE',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tbl-ember-12',
    restaurantId: 'rest-ember-02',
    tableNumber: '12',
    tableName: 'Smokepit Cellar 12',
    capacity: 6,
    qrCodeUrl: '/restaurant/ember-smokehouse/table/12',
    status: 'AVAILABLE',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Verde Botanica Categories
  {
    id: 'cat-verde-starters',
    restaurantId: 'rest-verde-01',
    name: 'Artisan Starters & Chaats',
    slug: 'starters',
    description: 'Crisp small plates, truffle kulchas & botanical creations',
    icon: '🌱',
    sortOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-verde-mains',
    restaurantId: 'rest-verde-01',
    name: 'Curries & Royal Mains',
    slug: 'mains',
    description: 'Slow-simmered gravies, hand-churned paneer & rich biryanis',
    icon: '🍲',
    sortOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-verde-breads',
    restaurantId: 'rest-verde-01',
    name: 'Tandoor Breads & Rice',
    slug: 'breads-rice',
    description: 'Butter naans, garlic laccha parathas & fragrant basmati',
    icon: '🫓',
    sortOrder: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-verde-drinks',
    restaurantId: 'rest-verde-01',
    name: 'Elixirs & Mocktails',
    slug: 'drinks',
    description: 'Cold-pressed infusions, artisan lassi & herbal spritzers',
    icon: '🍹',
    sortOrder: 4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-verde-desserts',
    restaurantId: 'rest-verde-01',
    name: 'Artisan Desserts',
    slug: 'desserts',
    description: 'Saffron pistachio tarts, baked rasgulla & cacao crumbles',
    icon: '🍰',
    sortOrder: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Ember Smokehouse Categories
  {
    id: 'cat-ember-appetizers',
    restaurantId: 'rest-ember-02',
    name: 'Wood-Fired Grills & Kebabs',
    slug: 'kebabs-grills',
    description: 'Charcoal-grilled succulent tikka, tandoori wings & skewers',
    icon: '🍢',
    sortOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ember-mains',
    restaurantId: 'rest-ember-02',
    name: 'Signature Curries & Gravies',
    slug: 'curries',
    description: 'Rich Old Delhi style butter chicken, rogan josh & dal bukhara',
    icon: '🍲',
    sortOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ember-breads',
    restaurantId: 'rest-ember-02',
    name: 'Clay Oven Breads',
    slug: 'breads',
    description: 'Crispy butter naan, smoked chili parathas & roomali rotis',
    icon: '🫓',
    sortOrder: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-ember-drinks',
    restaurantId: 'rest-ember-02',
    name: 'Craft Beverages & Shakes',
    slug: 'beverages',
    description: 'Smoked spice sodas, cold brews & thick milkshakes',
    icon: '🥃',
    sortOrder: 4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Verde Botanica Items
  {
    id: 'item-v1',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-starters',
    name: 'Truffle & Wild Mushroom Mini Kulchas',
    description: 'Mini leavened breads stuffed with sautéed chanterelles, black truffle butter, and cashew cream.',
    image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=600&q=80',
    price: 240.00,
    costPrice: 75.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: true,
    spicyLevel: 1,
    preparationTimeMin: 12,
    calories: 280,
    allergens: ['Gluten', 'Dairy', 'Tree Nuts'],
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-v2',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-starters',
    name: 'Crispy Avocado Papdi Chaat',
    description: 'Hass avocado tartare over crisp organic papdi, pomegranate pearls, mint-coriander emulsion, and tamarind glaze.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
    price: 210.00,
    costPrice: 60.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    spicyLevel: 1,
    preparationTimeMin: 10,
    calories: 260,
    allergens: ['Gluten', 'Dairy'],
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-v3',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-mains',
    name: 'Paneer Makhani Royale',
    description: 'Fresh farm malai paneer cubes slow-simmered in roasted tomato velouté, cashews, and aromatic kasuri methi.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
    price: 340.00,
    costPrice: 110.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: true,
    spicyLevel: 1,
    preparationTimeMin: 15,
    calories: 460,
    allergens: ['Dairy', 'Tree Nuts'],
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-v4',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-mains',
    name: 'Slow-Cooked Dal Botanica',
    description: 'Whole black lentils and rajma simmered for 24 hours on slow charcoal embers with cultured white butter.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    price: 290.00,
    costPrice: 70.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: true,
    spicyLevel: 1,
    preparationTimeMin: 12,
    calories: 390,
    allergens: ['Dairy'],
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-v5',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-breads',
    name: 'Butter Naan (2 Pieces)',
    description: 'Clay tandoor fired refined wheat flatbread, brushed with golden desi butter.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    price: 80.00,
    costPrice: 18.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    spicyLevel: 0,
    preparationTimeMin: 6,
    calories: 220,
    allergens: ['Gluten', 'Dairy'],
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-v6',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-breads',
    name: 'Garlic Chili Butter Naan',
    description: 'Hand-stretched dough topped with minced roasted garlic, green chili flakes, and fresh cilantro.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    price: 95.00,
    costPrice: 22.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    spicyLevel: 1,
    preparationTimeMin: 6,
    calories: 235,
    allergens: ['Gluten', 'Dairy'],
    sortOrder: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-v7',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-drinks',
    name: 'Kesar Pista Botanical Lassi',
    description: 'Thick hand-whisked organic yogurt infused with Kashmiri saffron strands and crushed green pistachios.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    price: 150.00,
    costPrice: 42.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    spicyLevel: 0,
    preparationTimeMin: 5,
    calories: 210,
    allergens: ['Dairy', 'Tree Nuts'],
    sortOrder: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-v8',
    restaurantId: 'rest-verde-01',
    categoryId: 'cat-verde-desserts',
    name: 'Baked Saffron Rasgulla Tart',
    description: 'Caramelized cottage cheese dumplings baked in saffron rabri reduction on almond date crust.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
    price: 190.00,
    costPrice: 55.00,
    isVeg: true,
    isAvailable: false, // For testing unavailable item state
    isFeatured: false,
    spicyLevel: 0,
    preparationTimeMin: 8,
    calories: 340,
    allergens: ['Dairy', 'Tree Nuts'],
    sortOrder: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Ember Smokehouse Items
  {
    id: 'item-e1',
    restaurantId: 'rest-ember-02',
    categoryId: 'cat-ember-appetizers',
    name: 'Smoked Angaar Chicken Tikka',
    description: 'Boneless chicken thigh chunks marinated in degi mirch, hung curd, and mustard oil, charred over charcoal.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
    price: 360.00,
    costPrice: 120.00,
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    spicyLevel: 2,
    preparationTimeMin: 15,
    calories: 440,
    allergens: ['Dairy', 'Mustard'],
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-e2',
    restaurantId: 'rest-ember-02',
    categoryId: 'cat-ember-mains',
    name: 'Old Delhi Classic Butter Chicken',
    description: 'Tandoor grilled chicken simmered in velvet satin tomato gravy with dried fenugreek and butter.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    price: 380.00,
    costPrice: 130.00,
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    spicyLevel: 1,
    preparationTimeMin: 18,
    calories: 590,
    allergens: ['Dairy', 'Tree Nuts'],
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-e3',
    restaurantId: 'rest-ember-02',
    categoryId: 'cat-ember-breads',
    name: 'Butter Naan (2 Pieces)',
    description: 'Clay tandoor fired refined wheat flatbread brushed with butter.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    price: 40.00,
    costPrice: 10.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    spicyLevel: 0,
    preparationTimeMin: 6,
    calories: 220,
    allergens: ['Gluten', 'Dairy'],
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-e4',
    restaurantId: 'rest-ember-02',
    categoryId: 'cat-ember-mains',
    name: 'Mutton Rogan Josh',
    description: 'Tender baby goat shank slow-braised in Kashmiri whole spices, ratanjot oil, and shallot broth.',
    image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=600&q=80',
    price: 460.00,
    costPrice: 170.00,
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    spicyLevel: 2,
    preparationTimeMin: 20,
    calories: 640,
    allergens: [],
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-e5',
    restaurantId: 'rest-ember-02',
    categoryId: 'cat-ember-drinks',
    name: 'Smoked Spiced Masala Soda',
    description: 'Crisp club soda with rock salt, roasted cumin, lime zest, and cold-smoked mint extract.',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    price: 110.00,
    costPrice: 24.00,
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    spicyLevel: 1,
    preparationTimeMin: 4,
    calories: 45,
    allergens: [],
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
